INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('eclavijo', md5('4374363') , 'EDINO CLAUDIO', 'CLAVIJO PONCE' , '4374363',1,1);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('kguibarra', md5('4777058') , 'KATHERINE SIMONE', 'GUIBARRA LARA' , '4777058',1,1);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('gpizarroso', md5('3391997') , 'GASTON RAMIRO SAMUEL', 'PIZARROSO LARA' , '3391997',1,1);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('rduarte', md5('3474237') , 'ROXANA JEANNETTE', 'DUARTE ABDALA' , '3474237',1,1);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('rramos', md5('4773231') , 'RICHARD MARCOS', 'RAMOS GALLER' , '4773231',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('cmontalvo', md5('2707142') , 'CLAUDIA NANCY', 'MONTALVO CATACORA' , '2707142',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('hpinedo', md5('6103223') , 'HERNANDO MACARIO', 'PINEDO MAMANI' , '6103223',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('mperez', md5('2695083') , 'MARCELO VLADIMIR', 'PEREZ LLANOS' , '2695083',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('rsejas', md5('4837083') , 'RAUL', 'SEJAS CARDENAS' , '4837083',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('msalvatierra', md5('6053385') , 'MIGUEL RUBEN', 'SALVATIERRA MURILLO' , '6053385',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('ochavez', md5('4798192') , 'OSCAR EDUARDO', 'CHAVEZ JIMENEZ' , '4798192',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('jecheverria', md5('3399271') , 'JOSE LUIS', 'ECHEVERRIA LOPEZ' , '3399271',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('vmichel', md5('4314752') , 'VIVIAN GRETEL', 'MICHEL ZAMBRANA' , '4314752',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('ecoronel', md5('3424081') , 'EDGAR MARCELO', 'CORONEL GUTIERREZ' , '3424081',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('cpabon', md5('3351044') , 'CINTYA DE LAS NIEVES', 'PABON BALDERAS' , '3351044',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('vrivas', md5('4321517') , 'VANIA', 'RIVAS BELLO' , '4321517',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('szuazo', md5('4824059') , 'SANDRA ORIANNA', 'ZUAZO SALGUEIRO' , '4824059',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('fcori', md5('5959210') , 'FANNY XIMENA', 'CORI CALLISAYA' , '5959210',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('ymendoza', md5('4377508') , 'YECID MAURICIO', 'MENDOZA OROPEZA' , '4377508',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('cveizaga', md5('6853549') , 'CAROLINA CECILIA', 'VEIZAGA PEÑALOZA' , '6853549',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('alozada', md5('6876508') , 'ANDREA MIRIAM', 'LOZADA ALCOCER' , '6876508',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('bpaez', md5('4816105') , 'BRYAN ALVARO', 'PAEZ SILVA' , '4816105',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('fmarin', md5('4912426') , 'FERNANDO YAMIL', 'MARIN IBAÑEZ' , '4912426',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('sgallardo', md5('6035516') , 'SAMUEL HECTOR', 'GALLARDO CUEVAS' , '6035516',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('cespinoza', md5('4828814') , 'CORINA RAQUEL', 'ESPINOZA ARIÑEZ' , '4828814',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('mmedrano', md5('2379547') , 'MARLENE MARGOTH', 'MEDRANO JIMENEZ' , '2379574',1,2);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('marequipa', md5('3328746') , 'MIRIAM VIRGINIA', 'AREQUIPA TEJERINA' , '3328746',1,2);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('cpeñaloza', md5('4906321') , 'CLAUDIA MICAELA', 'PEÑALOZA BALDERRAMA' , '4906321',1,2);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('ncalle', md5('4805783') , 'NILDA', 'CALLE MIRANDA' , '4805783',1,2);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('harteaga', md5('1904835') , 'HECTOR ENRIQUE', 'ARTEAGA HEREDIA' , '1904835',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('cmendieta', md5('3643586') , 'CINTHIA PATRICIA', 'MENDIETA CAMARGO' , '3643586',1,1);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('rberrios', md5('4825097') , 'RAMIRO ARIEL', 'BERRIOS SANDOVAL' , '4825097',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('arios', md5('9887630') , 'ARIEL FELIPE', 'RIOS FLORES' , '9887630',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('cgonzales', md5('5997844') , 'CRISTIAM BEYMAR', 'GONZALES HERRERA' , '5997844',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('dcanelas', md5('5949692') , 'DIEGO AMERICO', 'CANELAS SANTIESTEBAN ' , '5949692',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('elopez', md5('3470752') , 'EDGAR GUIDO', 'LOPEZ' , '3470752',1,1);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('dyanarico', md5('5953714') , 'DAVID MODESTO', 'YANARICO CERDA' , '5953714',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('pluna', md5('2286533') , 'PABLO MANUEL', 'LUNA LANDAETA' , '2286533',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('pzambrana', md5('6948448') , 'PAMELA VIVIAN', 'ZAMBRANA MARCONI' , '6948448',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('rherrera', md5('3449126') , 'RODRIGO CESAR', 'HERRERA RODRIGUEZ' , '3449126',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('afuentes', md5('2280811') , 'ALEIDA', 'FUENTES SANCHEZ' , '2280811',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('jlanda', md5('3818703') , 'JAVIER ALEJANDRO', 'LANDA MEDRANO' , '3818703',1,1);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('jbarron', md5('6034233') , 'JAHEL', 'BARRON VEIZAGA' , '6034233',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('jguzman', md5('5957132') , 'JAVIER ROLANDO', 'GUZMAN' , '5957132',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('ggutierrez', md5('6171709') , 'GROVER LUIS', 'GUTIERREZ MARCA' , '6171709',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('jvelasco', md5('3389111') , 'JAIME RIGOBERTO', 'VELASCO YUJRA' , '3389111',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('cborda', md5('6984120') , 'CHRISTIAN JAVIER', 'BORDA PETERS' , '6984120',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('drojas', md5('6112491') , 'DANIEL ALFONSO', 'ROJAS CAHUPAZA' , '6112491',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('sprudencio', md5('3455506') , 'SILVIA ALEJANDRA', 'ALARCON PRUDENCIO' , '3455506',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('lgarafulich', md5('6755312') , 'LYNN KATHERINE', 'GARAFULICH ROMERO' , '6755312',1,3);
INSERT INTO "adm_users" ("username", "password", "nombres", "apellidos", "numero_ci", "tipo_doc_ci", "role_id") VALUES('usprueba', md5('usprueba') , 'USUARIO', 'PRUEBA' , '5655312',1,1);

